packages:
  - frontend
  - backend

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@eslint/plugin-kit@<0.2.3': '>=0.2.3'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@nestjs/common@<10.4.16': '>=10.4.16'
  axios@<1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  formidable@>=3.1.1-canary.20211030 <3.5.3: '>=3.5.3'
  jsonpath-plus@<10.3.0: '>=10.3.0'
  multer@>=1.4.4-lts.1 <2.0.0: '>=2.0.0'
  multer@>=1.4.4-lts.1 <2.0.1: '>=2.0.1'
  multer@>=1.4.4-lts.1 <2.0.2: '>=2.0.2'
  nanoid@<3.3.8: '>=3.3.8'
  path-to-regexp@<0.1.12: '>=0.1.12'
  sha.js@<=2.4.11: '>=2.4.12'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.0.0 <5.4.15: '>=5.4.15'
  vite@>=5.0.0 <5.4.16: '>=5.4.16'
  vite@>=5.0.0 <5.4.17: '>=5.4.17'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  vite@>=5.0.0 <=5.4.11: '>=5.4.12'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
